regions:
  999:
    regionid: 999
    regioncode: schef
    regionname: "Schefenacker DERP"
    nodes:
      - name: vps-schefenacker
        regionid: 999
        hostname: vps.schefenacker.net
        ipv4: "194.164.49.35"
        derpport: 443
        stunport: 3478
        stunonly: false