server_url: https://vps.schefenacker.net
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 127.0.0.1:9090
grpc_listen_addr: 0.0.0.0:50443
grpc_allow_insecure: false

private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key

# Custom IP ranges for your network
prefixes:
  v4: 100.64.0.0/10        # IPv4
  v6: fd7a:115c:a1e0::/48  # IPv6

derp:
  server:
    enabled: true
    region_id: 999
    region_code: "schef"
    region_name: "Schefenacker DERP"
    stun_listen_addr: "0.0.0.0:3478"
    private_key_path: /var/lib/headscale/derp_server_private.key
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  paths:
    - /etc/headscale/derp.yaml
  auto_update_enabled: true
  update_frequency: 24h

disable_check_updates: false
ephemeral_node_inactivity_timeout: 30m

# Production database configuration
database:
  type: sqlite3
  sqlite:
    path: /var/lib/headscale/db.sqlite

acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: ""

tls_letsencrypt_hostname: ""
tls_letsencrypt_cache_dir: /var/lib/headscale/cache
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_listen: ":http"

tls_cert_path: ""
tls_key_path: ""

# Logging for production
log:
  format: json
  level: info

policy:
  path: ""

# DNS Configuration
dns:
  override_local_dns: true
  nameservers:
    global:
      - 1.1.1.1    # Cloudflare
      - 8.8.8.8    # Google backup
  search_domains: []
  magic_dns: true
  base_domain: schefenacker.vpn

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"